### ISSUE TITLE
Bug detected /quests/2

### ISSUE THREAD

**Issue by tanguilb** [WildCodeSchool/feedback#100]
Bonjour,

Sur la quête "Dans la peau d'un cornac" Je rencontre un petit souci. Quand je soumet mon lien pour valiadtion, il ne le prend pas en compte. Personne ne peut donc voir la solution que je propose et donc me la valider.

**Comment by Cookiie** [comment]
@tanguilb Peux-tu te rapprocher de ton formateur stp ? As-tu bien lié ton compte github ?

**Comment by Cookiie** [comment]
ticket resté dans réponse, je ferme
