### ISSUE TITLE
Erreur dans l'âge des submission des quêtes

### ISSUE THREAD

**Issue by cyril-lemaire** [WildCodeSchool/feedback#104]
l'affichage de l'âge des submission n'est pas cohérent entre la page "Evaluer mes pairs" (http://odyssey.wildcodeschool.fr/corrections) et la page de la solution.
La page évaluer mes pairs donne systématiquement des âges plus grands aux submissions que la page de la submission elle-même (jusqu'à une semaine de différence).

Exemples :
http://imgur.com/a/m2MHD -> "Evaluer mes pairs"
http://imgur.com/a/lUlfh -> Submission de Céline
http://imgur.com/a/4k65k -> Submission de Paul

**Comment by julienr114** [comment]
salut @RandsTaggle ,

Merci de ton retour,

C'est un problème que nous avions déjà identifié. On compte refondre prochainement cette page avec une nouvelle interface et donc résoudre se souci par la même occasion.
