### ISSUE TITLE
[Ancienne promo] Correction & Cie.

### ISSUE THREAD

**Issue by t-merlin** [WildCodeSchool/feedback#105]
Bonjour, Bonsoir,

Je suis un super wilder de la Promo 3 de La Loupe (un ancien donc).
Je souhaitais savoir si je pouvais corriger les propositions de nos chers poulains en devenir, ou pas du tout ? Car quand je me rends sur "Evaluer mes pairs", je retrouve des solutions datant de 3mois (alors que je pense que ça doit être un peu l'euphorie sur Odyssey)

Merci par avance ! 
Thomas

**Comment by julienr114** [comment]
Salut @OuterAlt,

Actuellement dans Odyssey les promos sont séparées en 'crew' et tu ne peux interagir qu'avec les membres de ton 'crew'. 

Il vrai que c'est dommage de ne pas pouvoir interagir avec tous le monde. Pour le moment ce n'est pas dans nos priorités mais c'est une fonctionnalité à laquelle nous réfléchissons, tu seras le premier informé si nous décidons de la mettre en place.
