### ISSUE TITLE
Problèmes affichage notifications et quêtes à finir

### ISSUE THREAD

**Issue by Aylarius** [WildCodeSchool/feedback#107]
Les notifications dans la nav ne sont pas disponibles depuis la page d'accueil (Parcours).
Et l'onglet "Quêtes à finir" apparaît alors qu'il est vide.
Ces deux problèmes sont présents sur Mac et Ubuntu.

<img width="1231" alt="problemes_odyssey_" src="https://cloud.githubusercontent.com/assets/19950092/18503104/6b702a28-7a5b-11e6-9264-e731bace3df4.png">

**Comment by julienr114** [comment]
Salut @Aylarius,

Nous sommes en train de migrer vers une nouvelle interface graphique. Actuellement seul la page d'accueil utilise notre nouvelle UI et nous allons changer notre système de notification c'est pourquoi elles n'apparaissent pas sur cette page. 

Pour ton problème de "Quête à finir" c'est un bug, merci de nous l'avoir retourné. On va tenter d'identifier la cause et de le résoudre
