### ISSUE TITLE
Bug mise à jour de quête

### ISSUE THREAD

**Issue by romaincoeur** [WildCodeSchool/feedback#109]
Il faut que je mette à jour une quête dont je suis l'auteur. Comment je m'y prends ?

**Comment by Cookiie** [comment]
@romaincoeur est-ce que tu peux nous préciser quel type de mise à jour tu veux faire, car actuellement on ne peut pas éditer une quête validée

**Comment by jum-s** [comment]
https://chat.wildcodeschool.fr/wildchat/pl/ncemyfcueifiuyjw774mrk81qc

**Comment by romaincoeur** [comment]
Il y a un changement dans le process d'attribution des licences Phpstorm. Au lieu que tous les élèves m'envoient un mail ils ont juste à cliquer sur un lient
