### ISSUE TITLE
Filtrage des solutions déjà corrigées

### ISSUE THREAD

**Issue by Balatzar** [WildCodeSchool/feedback#11]
Ce serait cool de pouvoir voir facilement sur [cette page](http://odyssey.wildcodeschool.fr/corrections) les solutions que l'on a pas encore corrigé parce que c'est un peu laborieux de devoir regarder les solutions une par une :)

**Comment by Em-AK** [comment]
Oui, on a prévu d'améliorer l'affichage des solutions. On va s'inspirer du fonctionnement d'une inbox, pour visualiser facilement les solutions qui ont déjà été lues, celles ou j'ai déjà posté un commentaire, celles que j'ai déjà validées.

**Comment by Em-AK** [comment]
@balatzar Des retours / suggestions par rapport à la livraison d'aujourd'hui ?

**Comment by Balatzar** [comment]
Ca marche impeccable ! faut que je me remette aux quêtes maintenant qu'on a fini avec erdf.
