### ISSUE TITLE
Bug detected /solutions/1906

### ISSUE THREAD

**Issue by JbPasquier** [WildCodeSchool/feedback#110]
Lorsque je poste un commentaire sans mettre le bouton en vert pour valider sans valider (>.<) un élève ;
Puis que deux élèves viennent valider la solution ;
Et que j'édite mon commentaire en passant la validation au vert ;
L'élève obtient bien 3 validations, mais sa quête n'est pas validée.

Solution temporaire appliquée, j'ai repassé mon 1er en rouge et ai fais un second commentaire en vert.

En plus clair : Une solution proposée avec deux verts et un rouge si on édite le rouge pour passe rà 3 verts, la quête n'est pas validée.

**Comment by julienr114** [comment]
@JbPasquier Tu peux nous dire sur quel élève c'est arrivé ?

**Comment by JbPasquier** [comment]
Benjamin Hoeffler, sur la solution #1906.

**Comment by edoume** [comment]
@JbPasquier Ok merci pour les infos l'aventure est validée en base pour moi.
C'est un bug de pouce à l'édition par un formateur

**Comment by Cookiie** [comment]
@edoume est-ce qu'on peut fermer ce ticket ?
