### ISSUE TITLE
Bug detected /notifications

### ISSUE THREAD

**Issue by kvn29** [WildCodeSchool/feedback#111]
Dans la quête http://odyssey.wildcodeschool.fr/tasks/5188, le lien http://javascript.didacto.net/ retourne une 502.

**Comment by Cookiie** [comment]
@kvn29 bien reçu, on regarde ;)

**Comment by Cookiie** [comment]
Vu avec JB, le site est bien HS, à priori c'est un pb récurrent. j'ai demandé aux formateurs s'ils avaient un autre tuto. En attente.

**Comment by kvn29** [comment]
D’accord, merci bien!

**Comment by Cookiie** [comment]
@JbPasquier a contacté le site, ça remarche :)
