### ISSUE TITLE
Quete "Installation php storm"

### ISSUE THREAD

**Issue by MkLHX** [WildCodeSchool/feedback#118]
#### Dans la section installe php storm sur ubuntu, la commande est :

> tar xfz PhpStorm-10.0.3.tar.gz
> ./phpStorm.sh
#### Hors sur le site de phpstorm, il ont certainements changer leur versionning et la commande est :

> Unpack the PhpStorm-2016.2.1.tar.gz file using the following command: 
>        tar xfz PhpStorm-2016.2.1.tar.gz
>    Run PhpStorm.sh from the bin subdirectory

**Comment by edoume** [comment]
@romaincoeur Hello Romain peux-tu regarder stp

**Comment by romaincoeur** [comment]
En effet il faut adapter l'énoncé à la version du fichier téléchargé. Mais on ne va pas changer la quête à chaque nouvelle version de phpstorm. Il faut juste que les étudiants réfléchissent un peu

**Comment by romaincoeur** [comment]
Je rajouterais un commentaire dans la quête pour leur dire

**Comment by JbPasquier** [comment]
Peut-être passer la commande avec un joker ?
tar xfz PhpStorm-*.tar.gz
./phpStom.sh
