### ISSUE TITLE
Mic Mac association solution / quest pour /users/37

### ISSUE THREAD

**Issue by naamelie** [WildCodeSchool/feedback#12]
Hello, j'ai un soucis dans mon espace, il m'affiche "Amélie a posté une nouvelle solution sur Discuter en SQL avec une base de donnée" mais cela m'amène sur ma solution git (solutions 108). 

D'ailleurs quand j'ai posté ma solution sql cela m'avait orienté vers ma solution git. 

;)

**Comment by Em-AK** [comment]
Merci pour le rapport de bug, j'investigue et je te tiens au courant.

**Comment by ghost** [comment]
Bonsoir au cas où, je rencontre le même soucis dans mon journal : http://odyssey.wildcodeschool.fr/users/37/journal
quand je clique sur "Amélie a posté une nouvelle solution sur Apprendre le Markdown"
j'arrive sur ma solution SQL http://odyssey.wildcodeschool.fr/solutions/120... 
Juste au cas où. 
Je vais essayer de vérifier quand je poste une solution pour un quête, j'ai l'impression que c'est là qu'il se passe quelque chose. (me renvoies à la quête que je suis en train de corriger pour quelqu'un d'autre...ou tout simplement la dernière quête que j'ai validé)
