### ISSUE TITLE
Problème validation quête xdebug

### ISSUE THREAD

**Issue by Gy0m** [WildCodeSchool/feedback#122]
Bonjour , j'ai posté une 1ere solution de la quète qui comportais une erreur, j'ai donc posté une deuxième solution qui a été validée 3 fois. Seulement ma quête apparais encore comme en cours, je pense qu'il attends une validation pour la 1ere solution. J'ai demandé une validation à mon prof seulement il ne me vois pas dans les quêtes à valider. Une petite aide serai bienvenue, merci

**Comment by edoume** [comment]
Problème de double aventure réglé, je clos

**Comment by Gy0m** [comment]
merci
