### ISSUE TITLE
Bug detected /quests/2

### ISSUE THREAD

**Issue by bruno-bouvet** [WildCodeSchool/feedback#124]
Impossible de poster ma solution.
Message:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by edoume** [comment]
@bruno-bouvet 
https://github.com/WildCodeSchool/feedback/issues/96#issuecomment-246356660
Cette solution fixe-t-elle ton problème?

**Comment by bruno-bouvet** [comment]
Toujours le même problème

**Comment by edoume** [comment]
**Bug Gist** http://odyssey.wildcodeschool.fr/solutions/2507
le contenu des fichiers présent dans le gist ne sont pas affichés

**Comment by edoume** [comment]
Le problème d'url n'étant pas un gist est corrigé, peux-tu réessayer et nous faire un retour.
Merci

**Comment by bruno-bouvet** [comment]
Salut, j'ai déjà validé la quête en retirant les images.

Bruno Bouvet
_Chargé de Marketing_
07 62 40 66 92
bouvet.bruno@gmail.com
http://www.bruno-bouvet.fr
Social: https://www.linkedin.com/in/brunobouvet
http://www.viadeo.com/profile/002ney08oxt7boj
https://twitter.com/techsquids

2016-09-26 16:02 GMT+02:00 Édouard notifications@github.com:

**Comment by Cookiie** [comment]
Hello @bruno-bouvet 
est-ce que c'est ok de ton côté pour que je ferme le ticket ?

**Comment by bruno-bouvet** [comment]
Bonjour Edouard,

On peut fermer le ticket,

Bonne journée.

Bruno.

Bruno Bouvet
_Développeur Junior /Marketing__, Com & Crea_
07 62 40 66 92
bouvet.bruno@gmail.com
http://www.bruno-bouvet.fr
Social: https://www.linkedin.com/in/brunobouvet
http://www.viadeo.com/profile/002ney08oxt7boj
https://twitter.com/techsquids

2016-10-10 12:38 GMT+02:00 Cookiie notifications@github.com:
