### ISSUE TITLE
Bug detected /quests/37

### ISSUE THREAD

**Issue by jgrom** [WildCodeSchool/feedback#126]
Salut ! Pour la quête "Découvrir le HTML5 et le CSS3", il est demandé de poster en solution le lien de son dépôt Github. En soumettant le lien, la solution n'est pas retenue, et un message affiche que l'url n'est pas au format gist. >> [screenshot](https://drive.google.com/open?id=0Bz_Jmp4fq6ODZWUzd1FFNXctZEU)

**Comment by edoume** [comment]
Le problème d'url n'étant pas un gist est corrigé, peux-tu réessayer et nous faire un retour.
Merci

**Comment by jgrom** [comment]
\o/ çà marche !! merci les gars :)
