### ISSUE TITLE
Quête Linkedin

### ISSUE THREAD

**Issue by dibattista** [WildCodeSchool/feedback#127]
Bonjour, J'ai un message d'erreur quand je veux mêtre mon URL : https://fr.linkedin.com/in/barbara-di-battista-710521b3 

Il me dit que ce n'est pas un gist . 

Est que je suis obliger de faire un Gist ? 

Merci

**Comment by edoume** [comment]
Le problème d'url n'étant pas un gist est corrigé, peux-tu réessayer et nous faire un retour.
Merci

**Comment by dibattista** [comment]
ca marche merci
