### ISSUE TITLE
quête à la découverte des BDD/ lien mort

### ISSUE THREAD

**Issue by Jasdero** [WildCodeSchool/feedback#128]
Le lien suivant http://www.supinfo.com/articles/single/548-introduction-methode-merise est mort 
sur cette page http://odyssey.wildcodeschool.fr/tasks/6597. Merci

**Comment by edoume** [comment]
@Jasdero le lien semble de nouveau actif, c'est bon pour toi?

**Comment by Jasdero** [comment]
oui c'est bon merci beaucoup

2016-09-27 9:21 GMT+02:00 Édouard notifications@github.com:
