### ISSUE TITLE
Bug detected /solutions/2608

### ISSUE THREAD

**Issue by stephsen** [WildCodeSchool/feedback#130]
Description du bug rencontré
Quête Javascripting validé alors que je n'ai aucune validation.
De plus la quête n'apparait pas dans "évaluer mes pairs" et de ce fait je ne peux valider personne.

**Comment by edoume** [comment]
Hello @stephsen, tu as bien 3 validations mais sur ta seconde itération,
tu peux y accéder directement via http://odyssey.wildcodeschool.fr/solutions/2610
ou lorsque tu es sur ta première solution, il y a un 1 et 2 à droite de MES SOLUTIONS ------- >
C'est bon pour toi?

**Comment by stephsen** [comment]
oui c'est ok pour moi.
merci

2016-09-27 12:05 GMT+02:00 Édouard notifications@github.com:
