### ISSUE TITLE
Bug detected /quests/42

### ISSUE THREAD

**Issue by acrobat22** [WildCodeSchool/feedback#132]
Lorsque je souhaite envoyer ma réponse, j'ai ce message d'erreur /
We're sorry, but something went wrong.
If you are the application owner check the logs for more information

Merci pour votre aide

**Comment by edoume** [comment]
Le gist créer était Anonyme (création non authentifié ou créé via le bouton "Create secret gist")
Le lien doit ressembler à celui-ci => https://gist.github.com/edoume/1349b76391f3d75ee8fe
avec ton pseudo GitHub dans l'url.

**Comment by Cookiie** [comment]
Hello @acrobat22 
est-ce que tu as réessayer d'envoyer ta réponse en suivant le commentaire de @edoume ci-dessus ?

**Comment by acrobat22** [comment]
J'ai suivi les indications et cela a fonctionné 
Merci à vous  
Envoyé de mon iPhone

**Comment by Cookiie** [comment]
top merci :)
Je ferme le ticket
