### ISSUE TITLE
Bug Quête Linkedin

### ISSUE THREAD

**Issue by ghost** [WildCodeSchool/feedback#133]
3 Validations mais quête toujours "en cours"

http://odyssey.wildcodeschool.fr/solutions/2703

![bugodyssey](https://cloud.githubusercontent.com/assets/22001964/19031306/b96490dc-8953-11e6-9d01-e70113a63c34.png)
![bugodyssey2](https://cloud.githubusercontent.com/assets/22001964/19031305/b94d2622-8953-11e6-9bf1-e900362477f6.png)

**Comment by edoume** [comment]
@gguesnet Désolé pour le bug, c'est bon pour toi?

**Comment by ghost** [comment]
C'est tout bon, ça fonctionne. Merci Edouard. :+1:
