### ISSUE TITLE
Bug detected /quests/6

### ISSUE THREAD

**Issue by MrDrannoc** [WildCodeSchool/feedback#137]
Bonjour,
Alors que l'on m'a déjà validé ma quête "linux tips", Odyssey considère que je suis toujours affecter à cette quête et je ne peux en sélectionner une autre, même en postant une deuxième solution...
Pouvez-vous me libérer de cette quête SVP ?

Merci
Kévin

**Comment by edoume** [comment]
Hello @MrDrannoc,
Désolé pour ce bug, c'est mieux?

**Comment by MrDrannoc** [comment]
C'est beaucoup mieux \o/
super merci.
