### ISSUE TITLE
Bug detected /tasks/315  where is the tutos ?

### ISSUE THREAD

**Issue by Suffren** [WildCodeSchool/feedback#14]
Il n'y a pas de liens associés avec cette page. J'imagine que c'etait les tutos de la page précédentes !

**Comment by Em-AK** [comment]
Merci de raporter ce bug. Le script de la quête a été mal chargé. Je vais creuser pour voir d'où ça viens.

En attendant voici les liens: 
- [Configurer Git sur sa machine](https://help.github.com/articles/set-up-git/#setting-up-git)
- [Configurer le cache de son mot de passe github dans git (HTTPS)](https://help.github.com/articles/caching-your-github-password-in-git/)
- [Communiquer avec Github via SSH](https://help.github.com/articles/generating-ssh-keys/)
