### ISSUE TITLE
Bloqué

### ISSUE THREAD

**Issue by MathieuM1** [WildCodeSchool/feedback#140]
Bonjour,
J'ai terminé la quête "Interagir avec une base de données grâce au langage SQL" depuis hier, elle a été validée par 3 personnes, mais elle est toujours au statut "en cours". Merci de me debloquer, car je ne peux pas commencer d'autres quêtes.

http://odyssey.wildcodeschool.fr/solutions/2736

Mercier Mathieu

**Comment by edoume** [comment]
Hello @MathieuM1,
C'est fait, désolé pour ce bug

**Comment by MathieuM1** [comment]
Super!
Merci pour ta réactivité,
A+
