### ISSUE TITLE
Problème - seules mes quetes faites sont affichées ! (voir line screenshot)

### ISSUE THREAD

**Issue by AF1890** [WildCodeSchool/feedback#141]
https://postimg.org/image/3k6qqqtgt/

**Comment by Cookiie** [comment]
@AF1890 il y a eu un bug en début d'après-midi, corrigé depuis. Est-ce que tu peux réessayer stp ?

**Comment by AF1890** [comment]
c'est bon depuis hier après-midi

merci !

_Aylin DE VILLECHENOUS_
_aylin.devillechenous@gmail.com aylin.devillechenous@capdigital.com_
Linkedin : _https://fr.linkedin.com/in/aylindevillechenous/
https://fr.linkedin.com/in/aylindevillechenous/_

Twitter : _https://twitter.com/AylinDigital
https://twitter.com/AylinDigital_
Tél : 06.89.93.33.31

2016-10-10 16:45 GMT+02:00 Cookiie notifications@github.com:

**Comment by Cookiie** [comment]
merci :)
Je ferme
