### ISSUE TITLE
Bug detected /quests/49

### ISSUE THREAD

**Issue by AF1890** [WildCodeSchool/feedback#143]
Hello

Je n'ai pas mis le bon lien dans ma quete.
Pouvez-vous s'il vous plait changer ce lien par celui-ci
https://github.com/AF1890/Projet_symfony/releases/tag/q_crud

**Comment by edoume** [comment]
@AF1890 Hello, pour cela tu peux simplement poster une nouvelle solution, et laisse un commentaire sur ton ancienne indiquant que le lien n'est pas le bon par exemple!

Tiens moi au courant ;)

**Comment by AF1890** [comment]
merci,

j'ai posté une nouvelle solution mais ça n'a pas écrasé l'ancienne.
J'ai en effet du coup indiué le bon lien en commentaire

2016-10-11 9:14 GMT+02:00 Édouard notifications@github.com:

**Comment by edoume** [comment]
@AF1890 Effectivement ton 'ancienne' solution n'est pas écrasée, cela fonctionne par itération, càd que tu as le droit à l'erreur et poster une nouvelle solution, tu la verras apparaitre comme dans l'image ci-dessous.

![solution-iter](https://cloud.githubusercontent.com/assets/8994056/19301266/e030d650-905e-11e6-8e9e-e99b1254ac2f.png)

Si tout est bon pour toi, je t'invite à clôturer l'issue ;)
Bonne journée
