### ISSUE TITLE
changement de design sur modeanalytics

### ISSUE THREAD

**Issue by CilooW** [WildCodeSchool/feedback#144]
hello, le site modeanalytics a revu complètement son interface, ce qui fait que cette quête n'est plus à jour :)

**Comment by Cookiie** [comment]
Hello @CilooW 
peux-tu préciser de quelle quête il s'agit stp ?

**Comment by CilooW** [comment]
première quête SQL : discuter en SQL avec une base de donnée 

j'ajoute des infos en commentaires. 
la colonne duration_hours n'existe plus, maintenant il y a une colonne duration (qui contient le temps en heure, minutes et secondes), et une colonne duration_seconds (un nombre correspondant au nombre de secondes de la colonne duration)
il y a une case précochée affichant limit 100 ce qui fait qu'on ne peut pas afficher 300 vélos à moins de le préciser dans la requête.
enfin, je ne comprends pas comment on peut arriver à un temps d'utilisation maxi de 175h, mais là, c'est peut être moi qui ne comprend pas! ^^

**Comment by Cookiie** [comment]
Merci @CilooW :) 
J'en parle avec les formateurs et on revient vers toi

**Comment by florianpdf** [comment]
Hello @CilooW 

```
la colonne duration_hours n'existe plus, maintenant il y a une colonne duration (qui contient le temps en heure, minutes et secondes), et une colonne duration_seconds (un nombre correspondant au nombre de secondes de la colonne duration)
```

Tu dois justement l'a créer --> [Alis SQL](http://sql.sh/cours/alias)

```
il y a une case précochée affichant limit 100 ce qui fait qu'on ne peut pas afficher 300 vélos à moins de le préciser dans la requête.
```

Essai de l'a décocher pour voir... et relance ta requete

```
enfin, je ne comprends pas comment on peut arriver à un temps d'utilisation maxi de 175h, mais là, c'est peut être moi qui ne comprend pas! ^^
```

Oui c'est bien toi, encore un ti peu de recherche ;-)

**Comment by Cookiie** [comment]
merci @florianpdf , je ferme le ticket

**Comment by CilooW** [comment]
@florianpdf oui bon pour la casé précochée, évidemment que je l'avais décochée... je trouvais simplement que l'énoncé du challenge était pas super clair sur ce point. idem pour la colonne duration hours. cependant, modeanalytics a tout de même changé son interface.
Merci, bonne journée.
