### ISSUE TITLE
Quête toujours en cours de correction alors qu'il y a bien trois validations

### ISSUE THREAD

**Issue by Aylarius** [WildCodeSchool/feedback#148]
Sur la quête Introduction PHP Orientée Objet, ma quête n'est toujours pas validée alors que j'ai bien mes trois corrections et que j'ai corrigé 4 personnes. Ce problème ne s'est pas produit pour mes camarades qui ont bien leur quête validée après avoir eu leurs trois corrections...

**Comment by edoume** [comment]
@Aylarius C'est mieux?

**Comment by Aylarius** [comment]
J'ai perdu toutes mes validations sur la quête :'(

**Comment by edoume** [comment]
Tu étais engagée deux fois sur la quête, j'ai supprimé la version non validée, peux tu me donner ton id de solution stp

**Comment by Aylarius** [comment]
J'ai pu l'ID de la solution vu que tout est supprimé chez moi. Là ça fait comme si j'avais jamais accepter le challenge, donc ma solution et mes validations ont été supprimées... Sinon ma solution c'était ce lien : https://gist.github.com/Aylarius/201956110ffa2663b07a23b0859abb3f

**Comment by Aylarius** [comment]
J'ai du refaire la quête en repostant et demandant de nouveau d'être validée mais sinon c'est bon
