### ISSUE TITLE
Bug detected /quests/63

### ISSUE THREAD

**Issue by stephsen** [WildCodeSchool/feedback#150]
Bonjour,

j'ai une erreur 500 lorsque j'essai de poster ma solution sur la quête NodejS.

voici mon lien Gist:
https://gist.github.com/stephsen/db41faedc12dc2f782b88f09bf9e20f5#file-node-js-quest

Merci

**Comment by edoume** [comment]
Hello @stephsen essayes comme ceci
https://gist.github.com/stephsen/db41faedc12dc2f782b88f09bf9e20f5
