### ISSUE TITLE
Annulation quête

### ISSUE THREAD

**Issue by Jipsian** [WildCodeSchool/feedback#154]
Hello les devs,

Est-ce que vous pouvez me désengagez de cette quête s'il vous plait : Interagir avec une base de données grâce au langage SQL ?

Paix et amour.

**Comment by Alfeo** [comment]
Courage Sylvain,
DO IT ! JUST DO IT !

_________________________

Florian DELABRE
*Développeur Web / PHP - Symfony2*

*LinkedIn :* https://lc.cx/4iak
*Github :* https://github.com/Alfeo

2017-01-06 11:45 GMT+01:00 Sylvain LABARRE <notifications@github.com>:
