### ISSUE TITLE
Lien inactif

### ISSUE THREAD

**Issue by thmeme** [WildCodeSchool/feedback#159]
Dans la quête "Commençons par apprendre à apprendre", le lien en bas de page de "Connais-toi avant de connaître le code" pour le "Test pour définir ton style d'apprentissage" n'est pas valide.

http://www.er.uqam.ca/nobel/k33560/octan/octests/testapprentissage.pdf

**Comment by emarmou** [comment]
Autre exemple avec du code java

https://odyssey.wildcodeschool.fr/creator/quests/70

[android_adapters.zip](https://github.com/WildCodeSchool/feedback/files/788229/android_adapters.zip)

**Comment by edoume** [comment]
@thmeme merci, problème remonté à l'auteur de la quête

@emarmou tu peux réuploader ta quête avec les modifications

**Comment by edoume** [comment]
@thmeme Ressource "Test pour définir ton style d'apprentissage" supprimée de la quête "Commençons par apprendre à apprendre"

@emarmou tu peux ouvrir un nouveau ticket stp
