### ISSUE TITLE
Erreur 500 validation quêtes Odyssey 

### ISSUE THREAD

**Issue by AslanBlack** [WildCodeSchool/feedback#160]
Bonjour, 

J'ai un problème pour valider les quêtes "Hello Github" et "Installer le SDK pour Android".

Je suis censé mettre un lien vers mon profil Github en guise de solution. Mais quand je fais ça, j'arrive sur une page Erreur 500.
Les autres élèves ont la même page lorsqu'ils essaient d'accéder à mes solutions.
Donc impossible pour eux de les valider. 

Please help :'( 

Kevin Anin (Toulouse)

**Comment by edoume** [comment]
Erreur fixée:
```
Author: edoume <iphone.courriel@gmail.com>
Date:   Thu Mar 2 17:07:54 2017 +0100
    fix github widget on solution when posting only a GH account
```
