### ISSUE TITLE
Quête Symfony (Génération du CRUD) [quests/49/steps/485]

### ISSUE THREAD

**Issue by splyy** [WildCodeSchool/feedback#169]
Si on suit le cours, il est demandé de suivre cette URL : 

> Allons voir maintenant ce qu'a fait Symfony. Rends-toi sur l'URL suivante : http://localhost/flyaround/web/app_dev.php/planemodel

Ce pendant cette dernière renvoit sur une erreur de permissions et ensuite de "SessionHandler". La quête pourrait préciser quoi faire dans ce cas ? 

Pour résoudre le soucis de **permission** : http://symfony.com/doc/current/setup/file_permissions.html

>  HTTPDUSER=`ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var
sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var

Ensuite pour l'erreur de **SessionHandle**, il suffit de remplacer `"%kernel.root_dir%/../var/sessions/%kernel.environment%"` par `"%kernel.root_dir%/../var/lib/php/sessions/%kernel.environment%"` dans le "save_path".

Sinon, préciser qu'on peut accéder à cette page lorsque le server marche (`bin/console server:start`) et que du coup l'URL serait : `http://localhost:8000/planemodel/`

Merci,

:)

**Comment by romaincoeur** [comment]
Je pense que cette issue témoigne du fait que le parcours Symfony a été construit sur la version 2.7 et qu'il faut le revoir en entier pour l'adapter.

**Comment by splyy** [comment]
Fort possible.
Après vu que le reste de la formation on utilise principalement le server `bin/console server:start` je pense pas que l'erreur soit la même.

Si besoin l'issue peut être close :)
