### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Moatti** [WildCodeSchool/feedback#172]
Hello, 

I would like to take courses and exercises for the Wilde Code School but the site does not work. There is error. ???

**Comment by edoume** [comment]
Hello,
Please try again now, waiting for your feedback.

Édouard

**Comment by edoume** [comment]
@Moatti I saw your solution, can i close this ticket?

**Comment by Moatti** [comment]
Hello,

Yes it’s ok , thank you!
Maéva
Le 24 mai 2017 à 16:47, Édouard <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hello,
Please try again now, waiting for your feedback.

Édouard
