### ISSUE TITLE
PB avec mon compte odyssey

### ISSUE THREAD

**Issue by bertrand84** [WildCodeSchool/feedback#175]
Bonjour 

l'ai un pb avec mon compte odyssey et cela fait 3 jouir que ça dur disque je clic sur relever les défis après avoir clique sur l'icône Mission candidat. pourriez vous voir d'où viens le problème?

Merci beaucoup et bonne fin d'après-midi.

Bertrand Smeyers

**Comment by bertrand84** [comment]
il me sort une erreur 500.

**Comment by edoume** [comment]
Bonjour,
Je vous invite à réessayer dès maintenant, dans l'attente de votre retour.

Édouard

**Comment by bertrand84** [comment]
C’est bon ça fonctionne Merci 

Bertrand
