### ISSUE TITLE
Typos javascripting

### ISSUE THREAD

**Issue by Balatzar** [WildCodeSchool/feedback#18]
Alors la 4ème tâche à effectuer est "Créé une page qui pose une question fermée (Oui/Non) au visiteur dans un prompt, puis qui affiche une alerte qui contient:" et là plus rien ! ^^

On met ce qu'on veut dans l'alerte du coup ? (bon c'est pas très important vu que c'est juste pour s'entrainer).

Et aussi j'en profite : ya une typo dans la 2 ("syntaxe JaveScript" au lieu de javAscript).

**Comment by Em-AK** [comment]
Merci. Un bug à la création de la quête... j'investigue !

Voilà toujours la fin de la phrase:

---

Créé une page qui pose une question fermée (Oui/Non) au visiteur dans un prompt, puis qui affiche une alerte qui contient:
- `1` si la réponse commence par 'o', 'O', 'y' ou 'Y',
- `0` si la réponse commence par 'n' ou 'N',
- `-1` dans tous les autres cas.
