### ISSUE TITLE
Affichage des tasks dans l'ordre inverse detected /tasks/339

### ISSUE THREAD

**Issue by EnteJulien** [WildCodeSchool/feedback#19]
Lorsque je suis sur la page http://odyssey.wildcodeschool.fr/tasks/340 et que je clique sur "suivant", je reviens à la page http://odyssey.wildcodeschool.fr/tasks/339

**Comment by Em-AK** [comment]
Merci pour cette remontée de bug.
En effet ce n'est pas normal du tout que les étapes s'affichent de la dernière à la première...

**Comment by Em-AK** [comment]
@EnteJulien Je viens de déployer une correction de ce bug.
Fais moi signe si l'erreur est encore présente pour toi.
