### ISSUE TITLE
Un formateur ne peux pas évaluer un autre formateur si lui même n'a pas fait la quête

### ISSUE THREAD

**Issue by jbehuet** [WildCodeSchool/feedback#2]

**Comment by jbehuet** [comment]
idem pour les solutions des élèves

**Comment by Em-AK** [comment]
Le bug est intégré au backlog d'Odyssey.

**Comment by Em-AK** [comment]
Bug reformulé:

Quand un formateur n'a jamais posté de solutions, il ne peut pas voir les solutions des élèves ou formateurs.

Bug corrigé (même si tu aura du mal à le vérifier maintenant que tu as des solutions en ligne) ;)
