### ISSUE TITLE
Bug detected /quests/3

### ISSUE THREAD

**Issue by julienr114** [WildCodeSchool/feedback#20]
Une erreur dans la consigne. Il n'y pas de colone duration_hours mais une colone duration ou une autre duration_secondes ou le temps est reporté en seconde.

**Comment by Em-AK** [comment]
Ce n'est pas une erreur de la consigne. Il faut que le résultat de ta query SQL retourne 2 colonnes dont une qui s'appelle `duration_hours` qu'il va falloir créer à partir des données existantes.
