### ISSUE TITLE
Les liens vers les itérations ne respecte pas l'ordre chronologique

### ISSUE THREAD

**Issue by Sl0b** [WildCodeSchool/feedback#22]
Je n'ai plus de bouton validé sur http://odyssey.wildcodeschool.fr/solutions/154
Je l'ai encore ailleurs.
Je fais cette remarque alors que je n'y vois actuellement que 2 validations et pourtant la solution a disparu pour moi de la page Evaluer mes pairs.

Edit: Je rajoute que j'ai vidé mon cache, cookies etc...

**Comment by Em-AK** [comment]
Merci de faire remonter ce problème.
Je pense que la cause viens de l'ordre des solutions qui n'est pas bon. La dernière devrait être la N°4 et non la N°1.

**Comment by Em-AK** [comment]
@Sl0b le bug est corrigé ;)
