### ISSUE TITLE
Afficher les solutions bonus dans le log /users/27

### ISSUE THREAD

**Issue by florianpdf** [WildCodeSchool/feedback#23]
Hello
J'en ai parlé à Edouard, il serait intéressant de faire réaparaitre les quetes lorsque l'on post un bonus. 
Par exemple, dans la quete SQL, j'ai posté une première fois la résolution de ma quete, elle m'a été validé, j'ai ensuite posté des reps supplementaire (pour les bonus) mais ces dernières n'apparaissent plus.
J'espère avoir été clair.

**Comment by Em-AK** [comment]
Oui j'en ai discuté avec Lucie. Pour l'instant le mieux à faire est de partager le lien de ta solution avec quelqu'un pour avoir du feedback.

C'est une fonctionnalité qu'on traitera une fois que la liste des solutions aura été réorganisée.
