### ISSUE TITLE
Inversion des tâches

### ISSUE THREAD

**Issue by Balatzar** [WildCodeSchool/feedback#24]
Dans la Linux tips (mais dans les autres aussi j'ai l'impression), l'odre des taches est inversé : c'est à dire que c'est à partir de la tâche "Enregistrer des vidéos de son terminal avec asciicinema" que je peux faire suivante et toute les faire jusqu'à arriver à "Installer un programme depuis la ligne de commande" qui ne me propose que de retourner à la quête.

**Comment by Em-AK** [comment]
en cours de résolution.
voir #19
