### ISSUE TITLE
Afficher le nombres de corrections

### ISSUE THREAD

**Issue by Inso-61** [WildCodeSchool/feedback#26]
Dans http://odyssey.wildcodeschool.fr/corrections,
Au dessus de filtres et solutions : "X CORRECTIONS EFFECTUÉES AUJOURD'HUI". ne devrait t-il pas afficher le nombre de correction plutôt que un "X" . :-)

**Comment by Em-AK** [comment]
C'est une fonctionalitée qui n'est pas encore implémentée ^^

**Comment by Cookiie** [comment]
@Em-AK vu que c'est une des fonctionnalités prévues dans la refonte, je peux clore ce ticket ici ?

**Comment by julienr114** [comment]
Plus d'actualité je clos
