### ISSUE TITLE
Problème de navigation dans les étapes d'une quête

### ISSUE THREAD

**Issue by romaincoeur** [WildCodeSchool/feedback#3]
Quand je clique sur le bouton valider la dernière étape je suis redirigé vers la première et celle-ci n'est plus validée.

**Comment by Em-AK** [comment]
@edoume a corrigé ça. Le comportement des chaeckboxes est maintenant cohérent sur l'ensemble des vues.

Fais moi signe si tu trouve des comportements suspects.
