### ISSUE TITLE
Echec Import d'une ressource avec du markdown multiligne comme description

### ISSUE THREAD

**Issue by Suffren** [WildCodeSchool/feedback#31]
"Visualizing Git Concepts"

Il n'y a pas de commandes associées à la description :)
http://odyssey.wildcodeschool.fr/tasks/485

tchao !

**Comment by Em-AK** [comment]
Quand je parle de commande, il s'agit des commandes git, ie les liens à cliquer sur la page de la ressource ;)

EDIT;
oups oui en effet j'ait fait une petite liste des commandes essentielles ^^
