### ISSUE TITLE
Quête vide, outils php

### ISSUE THREAD

**Issue by Balatzar** [WildCodeSchool/feedback#32]
Les instructions de la quêtes sont vides ^^ Et les critères de validation indiquent 'TODO'.

Je suis un éclaireur en fait !

**Comment by Balatzar** [comment]
Et par cette quête j'entend [cette quête](http://odyssey.wildcodeschool.fr/quests/8)

**Comment by Em-AK** [comment]
Balthazar l'explorateur ^^
