### ISSUE TITLE
Bug detected /quests/12

### ISSUE THREAD

**Issue by Celine-Langlade** [WildCodeSchool/feedback#33]
Y manque des lettres dans la description. Dans l'encadré blanc les mots sont coupés ><

**Comment by Em-AK** [comment]
Oui c'est normal, c'est un screenshot du fichier markdown pour illustrer ce que je dis juste au dessus ;)

**Comment by Celine-Langlade** [comment]
Oki pardon alors

Envoyé de mon iPad
