### ISSUE TITLE
Bug detected /quests/11

### ISSUE THREAD

**Issue by Inso-61** [WildCodeSchool/feedback#36]
je rencontre le message d'erreur suivant quand je tente d'envoyer ma solution quete n11 -> We're sorry, but something went wrong. If you are the application owner check the logs for more information.

**Comment by Inso-61** [comment]
![capture du 2015-09-22 09 22 49](https://cloud.githubusercontent.com/assets/8283515/10012800/9257f432-610b-11e5-98ce-5189ed564786.png)

**Comment by Em-AK** [comment]
Fixed
