### ISSUE TITLE
Bug detected /users/15/journal

### ISSUE THREAD

**Issue by sev28** [WildCodeSchool/feedback#39]
ma quête javascripting à été validée mais apparait toujours dans les quêtes en cours

**Comment by Em-AK** [comment]
C'est toujours le cas ?
Tu veux dire quand tu va sur la page "Mon Parcours" ?

**Comment by sev28** [comment]
oui quand je vais sur mon profil il est bien indiqué que ma quête javascripting a bien été validée mais elle apparait toujours dans mon parcours/quêtes en cours. 
Et j'ai 5 personnes qui ont validé  ma quête donc normalement elle aurait dû disparaitre des quêtes en cours mais est toujours là et du coup je ne peux pas passer à une autre quête vu que j'ai aussi la quête de Ruby.new en cours

**Comment by Em-AK** [comment]
J'enquête et je te tiens au courant.

**Comment by Em-AK** [comment]
La méthode `update_status` ne s'est pas exécutée sur l' `Adventure` concernées lorsqu'un commentaire a été posté.

Rustine:
J'ai exécuté `update_status` sur toutes les `Adventure`s de la base, depuis la console.

Je cherche toujours pourquoi `update_status` n'est pas appelé.

**Comment by Em-AK** [comment]
Les validation du modèle `Adventure` s'éxecutent lors de l'update. Ce qui provoque un échec, puis Rollback de la mise à jour du status de l'aventure.

J'extrais l'action d'accepter un challenge dans un interacteur, qui contiendra les validations en question, afin d'en libérer le modèle.

**Comment by Em-AK** [comment]
@sev28 le problème devrais être réglé.
Tu peux me confirmer ?

**Comment by sev28** [comment]
c'est ok les quêtes sont bien validéesMerci à toi 

Date: Wed, 30 Sep 2015 04:40:15 -0700
