### ISSUE TITLE
[Quête 3 - SQL query] Nommer les colonnes

### ISSUE THREAD

**Issue by emaestracci** [WildCodeSchool/feedback#4]
La collone 'duration_hours' n'existe pas, les deux collones en rapport avec le temps s'appelent 'duration' et 'duration_seconds'.

Emmanuel

**Comment by Em-AK** [comment]
Bonjour @emaestracci,

C'est à toi de donner un nom à ces colonnes via ta requête SQL.
Tu va devoir aller piocher dans les colonnes existantes, effectuer des opérations dessus, et donner un nom à la colonne de résultats.

**Comment by Em-AK** [comment]
Hello @emaestracci,
Tu as pu avancer sur ce point ou tu veux un coup de main ?

**Comment by emaestracci** [comment]
Salut Émilien,
Pas de soucis, je l'ai presque terminée (il ne me reste plus qu'à trouver la syntaxe pour la division par 3600).

Merci 
Emmanuel
