### ISSUE TITLE
Bug detected /quests/8

### ISSUE THREAD

**Issue by Ava78** [WildCodeSchool/feedback#40]
Description du bug rencontré

Ce n'est pas un bug, désolée, mais est ce possible de fermer cette quete, car elle m'empeche de faire la quete RUBY. Et je ne souhaite pas la faire. pour le moment.

Merci beaucoup

**Comment by Em-AK** [comment]
@ava78 Je t'ai désengagé de cette quête, c'est bon pour toi ?
