### ISSUE TITLE
Colorer la syntaxe du code dans les commentaires

### ISSUE THREAD

**Issue by Inso-61** [WildCodeSchool/feedback#44]
Il serait sympa de pouvoir écrire du code dans les commentaires et qu'il soit coloré et indenté automatiquement.

**Comment by Em-AK** [comment]
En théorie c'est déjà possible avec le markdown comme plus bas. En pratique, le CSS foire la mise en page du code.
Je met cette amélioration au menu d'Edouard pour cette semaine.

```
~~~ruby
class Fixnum
  def fizzbuzz
    # awesome code!
  end
end
~~~
```

Résultat attendu :

``` ruby
class Fixnum
  def fizzbuzz
    # awesome code!
  end
end
```
