### ISSUE TITLE
Bug detected /quests/15

### ISSUE THREAD

**Issue by Sl0b** [WildCodeSchool/feedback#47]
Pic dans le header qui s'amuse
![screenshot from 2015-10-20 14 34 28](https://cloud.githubusercontent.com/assets/11925412/10607134/c4b925b2-7737-11e5-9ee3-79a2f209f259.png)

**Comment by Em-AK** [comment]
Oups ^^

C'est mieux maintenant ?

**Comment by Sl0b** [comment]
Si senior
