### ISSUE TITLE
Pouvoir marquer toutes les notifications comme vues/lues

### ISSUE THREAD

**Issue by jbehuet** [WildCodeSchool/feedback#5]

**Comment by Em-AK** [comment]
On va enrichir le contenu d'une notification dans un premier temps pour donner plus de contexte avant de cliquer dessus.

**Comment by Em-AK** [comment]
@jbehuet c'est maintenant possible de marquer toutes les notificcations comme lues en une action ;)
http://odyssey.wildcodeschool.fr/notifications
