### ISSUE TITLE
Bug detected /notifications

### ISSUE THREAD

**Issue by JbPasquier** [WildCodeSchool/feedback#52]
Bonjour,

J'ai une notification qui ne fonctionne pas.
Elle est appelée "translation missing: fr.vote.created"
Elle pointe sur "http://odyssey.wildcodeschool.fr/notifications/3541/validate"
Elle mène vers "http://odyssey.wildcodeschool.frshares/130" (Manque un "/")

Je pense qu'il s'agit d'une notification d'upvote sur une ressource.

Merci !

**Comment by Em-AK** [comment]
Merci pour la notification ! 
J'ai relevé l'erreur aussi de mon coté. Il s'agit bien de l'upvote.
On règle ça rapidement.

**Comment by Em-AK** [comment]
Le bug a été corrigé !
Tu peux voter l'esprit tranquille ;)
