### ISSUE TITLE
/quests/1 - URL de la solution refusée

### ISSUE THREAD

**Issue by paul-ka** [WildCodeSchool/feedback#54]
Bonjour l'équipe, 
J'ai un problème quand j'essai de poster une solution sur la quête "Gist in the CLI",
je met le lien de ma solution, clique sur envoyer et j'ai ce message d'erreur:

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

Par avance merci

**Comment by Em-AK** [comment]
Hello @paul-ka !

Je vois que tu as essayé de poster le lien https://gist.github.com/paul-ka comme solution. Cette URL correspond à ton espace utilisateur, qui regroupe tous tes gists.

Si tu lis bien la consigne du challenge les 3 fichiers doivent se trouver dans le même gist.

Pour résumer
1 gist = une URL (du type https://gist.github.com/paul-ka/[chiffres_et_lettres])
et un gist peux contenir plusieurs fichiers.

Relis le [README](https://github.com/defunkt/gist#gist1----upload-code-to-httpsgistgithubcom) de la gem gist pour voir comment uploader plusieurs fichiers dans le même gist.
;)

**Comment by paul-ka** [comment]
Merci, C'était bien ça qui bloquait. Ca marche...

**Comment by Em-AK** [comment]
:+1:
