### ISSUE TITLE
Suggestion - Afficher qui fait la quête

### ISSUE THREAD

**Issue by JbPasquier** [WildCodeSchool/feedback#55]
Bonjour,

Suggestion lors de la réalisation de quête, afficher ceux qui l'ont aussi "En cours" dans le groupe (Avec un beau lien vers le Mattermost ?).
Cela permettrait de savoir vers qui on peut aller si on a un doute, une incompréhension. :-)

**Comment by Em-AK** [comment]
Bonne idée :)

**Comment by Em-AK** [comment]
## Histoire utilisateur

En tant qu'étudiant,
Je peux voir les étudiants qui sont engagés dans la même quête que moi
Afin de me mettre en contact avec eux quand j'ai des questions

## Scénario de validation

Soit un étudiant sur la page d'accueil d'une quête
Quand je clique sur le boutton **Challenge accepted !**
Alors je vois la liste de tous les étudiants qui se sont déjà engagés dans cette quête
Et cette liste s'affiche sur toutes les étapes relatives à la quête

**Comment by Em-AK** [comment]
Liste des étudiants de mon Crew "En cours" sur la même quête :
![wireframe_users_en_cours](https://cloud.githubusercontent.com/assets/1518393/13174867/ce4e3c32-d706-11e5-9537-0a6424aff628.jpg)

Détail d'une miniature de l'image de profil au hover : 

![wireframe_miniature_user](https://cloud.githubusercontent.com/assets/1518393/13174885/ea96299a-d706-11e5-83da-afe8f622837a.jpg)

**Comment by Em-AK** [comment]
Done !
Merci @JbPasquier et @JeremBe pour l'idée

et :+1: @edoume pour la réalisation

![scr done](http://storage2.static.itmages.com/i/16/0229/h_1456778826_9223055_2f39d363af.png)
