### ISSUE TITLE
Bug detected /quests

### ISSUE THREAD

**Issue by qgallois** [WildCodeSchool/feedback#56]
Les autres membres de la formation ne peuvent pas valider mes quêtes. Certainement parce que mon compte date de la session 2015. Malgré que j'ai pu terminer d'autres quêtes l'année dernière et qu'elles sont toujours considérée comme accomplis, je ne peux pas non plus corriger mes collègues.

**Comment by Em-AK** [comment]
Je regarde ça, j'ai du te laisser dans la promo d'avant.

**Comment by Em-AK** [comment]
Mhmm tu est bien dans la promo 3 sur Odyssey.
Est-ce que tu rencontre toujours les problèmes décrits ?

**Comment by qgallois** [comment]
Non tout a été remis dans l'ordre. 
Il me semble que Vincent s'en est chargé
