### ISSUE TITLE
Suggestion / Utiliser emoji.codes

### ISSUE THREAD

**Issue by JbPasquier** [WildCodeSchool/feedback#57]
Bonjour,

Sur Odyssée, en plus du markdown, ça porurait être chouette d'avoir accès aux émotes d'emoji.codes !

**Comment by Em-AK** [comment]
C´est vrai que les émoticones c´est la classe :sunglasses:

**Comment by jum-s** [comment]
pas a l'ordre du jour pour l'instant mais ce serait chouette
