### ISSUE TITLE
Bug detected /solutions/32

### ISSUE THREAD

**Issue by webdev33** [WildCodeSchool/feedback#6]
Le gist n'est pas exécuté, c'est le lien qui s'affiche.
Romain

**Comment by Em-AK** [comment]
Bonjour @webdev33,
est-ce que tu peux me donner le lien de la solution où tu as rencontré ce problème ?

**Comment by Em-AK** [comment]
Bonjour @webdev33,

Il te suffit de mettre à jour ton identifiant github avec `webdev33` sur ton profil ;)
http://odyssey.wildcodeschool.fr/users/22

**Comment by webdev33** [comment]
Merci ;-)

2015-09-02 18:13 GMT+02:00 Emilien <notifications@github.com>:
