### ISSUE TITLE
Acceder a la totalite du journal /users/59

### ISSUE THREAD

**Issue by the-dsw** [WildCodeSchool/feedback#60]
Description du bug rencontré

je n'ai plus d'acces a mon journal

je ne vois que le 20 derniere

**Comment by Em-AK** [comment]
Merci pour l´alerte. Je vais regarder ça.

**Comment by jum-s** [comment]
Après avoir commencé une migration, je trouve çà dommage de stocker l'url en base (çà fait une requete en plus sur toutes les pages)
Stocker dans un fichier config/hackpads.yml semble plus performant. Niveau sécurité si jamais un petit malin trouve les urls, l'authentification sur le site hackpad fera le tri, elle peut donc etre publique dans le code avec en clé la localisation du crew et en valeur l'url

**Comment by Em-AK** [comment]
Je crois que tu t'est trompé de ticket @jum-s
