### ISSUE TITLE
Comment démarrer la quête HTTP Request ?

### ISSUE THREAD

**Issue by vibesharing** [WildCodeSchool/feedback#61]
Quête difficile d'accès à première vue en ayant aucune expérience sur le sujet xml.
-Les ressources pourraient commencer d'un niveau plus bas et on pourrait être un peu plus guidé.

**Comment by Em-AK** [comment]
Tu as essayé de jouer avec le code présent dans la documentation ? soit dans la console de ton navigateur, soit sur [JS Bin](http://jsbin.com/?html,js,console,output)

Je te propose d'essayer de fomuler une question précise.
cc @jbehuet
