### ISSUE TITLE
Bug detected /tasks/2002

### ISSUE THREAD

**Issue by JokerHAHAHA** [WildCodeSchool/feedback#62]
je ne comprends pas : 

-l'axe EC-CA (action-abstraction)
- l'axe OR-CA (réflexion-expérimentation), 

Il y a deux fois le même axe....   ("CA") : normal ?

**Comment by Em-AK** [comment]
Je ne suis pas sur de comprendre la question. Il s´agit d´une remarque par rapport à une ressource de cette étape ?

http://odyssey.wildcodeschool.fr/tasks/2002
