### ISSUE TITLE
Ceci n'est pas une erreur mais des demandes!

### ISSUE THREAD

**Issue by Ncapron** [WildCodeSchool/feedback#65]
Bonjour,
Sur odyssey, il y a 2 collones avec "Quêtes achevées/Quêtes en cours" et donc je voulais juste proposer 2 choses pour le même "soucis"

**1) Solution aux Quêtes**
Donc soit une 3ème colonne avec un indicatif "attente de validation" qui ajouterai les quêtes après que l'on ait proposé une solution à celles ci.///

Soit simplement que les quêtes en cours soient en bleu et dès que l'on propose une solution la couleur autour du nom de la quête par exemple "Hello Github" changerait de couleur et deviendrait par exemple Jaune. (personellement je préfère cette solution)

Car actuellement, on se perd un peu entre les quêtes terminées et en attente de celles où odyssey attend de nous une solution!
**

**2) Savoir le nombre de validation**

Ma deuxième demande serait pour les quêtes en cours de validation (3ème colonne ou changement de couleur) une indication sur le menu "mon parcours" (on peut garder le pouce en l'air comme actuellement lorsque l'on évolue nos pairset une bulle pour savoir si il a mis un commentaire) car actuellement nous devons aller dans la quête en cours afin de voir tout ça or on ne sait pas forcément pour quelle quête on a proposé une solution, la structure du site sera toujours la même car nous prenons 2 quêtes par 2 quêtes et donc une fois 'challenge accepted', la quête se met à droite (comme actuellement btw) et juste avoir le pouce qui s'affiche directement sur cette page.

**Comment by Ncapron** [comment]
Propositions pour le site.

**Comment by Ncapron** [comment]
Et je n'ai pas trouvé le moyen d'envoyer une demande sans passer par la case "issues" car dans le "SOS" n'importe quel bouton me ramène ici.

**Comment by jum-s** [comment]
merci pour ces retours, c'est le bon endroit car cela reste un feedback de ton XP de la plateforme ;)
On va changer l'agencement bientot
