### ISSUE TITLE
Bug detected /quests/1

### ISSUE THREAD

**Issue by Deimokle** [WildCodeSchool/feedback#66]
Description du bug rencontré
Hello, j'ai ce message qui s'affiche lorsque je poste une solution sur le quête "Gist in the CLI"

{"base"=>["Url is not gist owner"]} 

Ce message apparaît lorsque je poste ce lien en solution: https://gist.github.com/0ebe784945c33a33345d
Le lien me paraît pourtant correct.

Par avance merci

**Comment by jum-s** [comment]
Salut
Sur Odyssey, as-tu bien renseigné ton profil avec le meme nom que ton compte github ?
On va voir çà de notre coté aussi

**Comment by Deimokle** [comment]
Effectivement, my bad, mon pseudo Github etait mal renseigné.
Par contre je viens de la modifier mais toujours le même problème.
