### ISSUE TITLE
Bug detected /tasks/2319

### ISSUE THREAD

**Issue by niwi84** [WildCodeSchool/feedback#68]
Description du bug rencontré
nous sommes plusieurs à ne pas réussir à installer xdebug, manquerait-il des instructions ou y a-t-il une quête à faire avant ?
Merci.

**Comment by romaincoeur** [comment]
Ce bug est lié à l'ordre des étapes. Comme les étapes sont chargées à l'envers les élèves sont perdus.

**Comment by romaincoeur** [comment]
Il faut commencer par la dernière étape et finir par la première

**Comment by Em-AK** [comment]
@romaincoeur le bug sur l'ordre des étapes ne concerne que la vue du rédacteur, pas celle des étudiants. Le problème dans l'install doit venir d'ailleur.

![quete_xdebug](https://cloud.githubusercontent.com/assets/1518393/14991288/e64771c0-1160-11e6-8ec7-5fa6e1d345c2.png)

@niwi84 Est-ce que tu peux détailler plus précisémment ton problème pour nous aider à cibler la cause :
- Les étapes que tu as suivi ?
- Le résultat que tu obtiens ?
- Le résultat que tu attendais ?

**Comment by romaincoeur** [comment]
![selection_067](https://cloud.githubusercontent.com/assets/5744428/14992013/6e59c4c0-1164-11e6-9dfd-631d4d39917d.png)
Moi je les ai dans le désordre
