### ISSUE TITLE
Bug detected /corrections

### ISSUE THREAD

**Issue by JbPasquier** [WildCodeSchool/feedback#69]
Quand je vais sur Evaluer mes pairs,
Dans la liste des solutions non commentées, j'ai de quelques liens qui pointent vers "http://odyssey.wildcodeschool.fr/adventures/*", avec un nombre à la place de l'étoile.
Je ne peux les consulter "Désolé Jean-Baptiste, cette page n'est pas pour toi".

![image](https://cloud.githubusercontent.com/assets/14278890/14768381/0d9a3914-0a41-11e6-8a4d-94624eb774a6.png)
## 

Quand je vais sur Evaluer mes pairs,
Je ne peux cliquer sur Toutes les quêtes, rien ne se passe.
## 

Quand je vais sur une solution proposée par un autre utilisateur,
Je remarque que même avec 4 validations, sa quête n'est pas passée (voir http://odyssey.wildcodeschool.fr/solutions/898 ).

**Comment by Cookiie** [comment]
@edoume

**Comment by edoume** [comment]
@JbPasquier Je viens de te rajouter une validation, peux-tu nous faire un retour?

Tu en avais 3, j'ai rajouté une 4ème

**Comment by JbPasquier** [comment]
@edoume Wow, aucune idée. C'est du très très vieux ça ! (5 mois)

**Comment by edoume** [comment]
@JbPasquier  Dis moi si ta quête est finalement validée?
