### ISSUE TITLE
Erreur si https dans le lien d'un gist solution

### ISSUE THREAD

**Issue by charlesnannan** [WildCodeSchool/feedback#7]
**Quête : Gists in the CLI**

Si l'on soumet un lien commençant par "https", Odyssey affiche une page d'erreur ("We're sorry, but something went wrong. If you are the application owner check the logs for more information.") Avec "http", aucun problème.

**Comment by Em-AK** [comment]
J'essaye de reproduire le bug et je te tiens au jus.

**Comment by Em-AK** [comment]
@charlesnannan J'ai la solution, il te suffit de mettre à jour ton identifiant github avec `charlesnannan` sur ton profil utilisateur ;)
http://odyssey.wildcodeschool.fr/users/14
