### ISSUE TITLE
Bug detected /tasks/2857

### ISSUE THREAD

**Issue by xkenzzo31** [WildCodeSchool/feedback#76]
Lien Mort https://format30.com/2012/02/29/quel-etudiant-etes-vous/ pour savoir quelle type d'étudiant je suis

**Comment by Em-AK** [comment]
Hello @xkenzzo31,
Le lien que tu fournis fonctionne pourtant chez moi :/

**Comment by Cookiie** [comment]
le lien fonctionne aussi de mon côté, c'était peut-être une indispo momentanée, je clos le ticket
