### ISSUE TITLE
Bug detected /tasks/2851

### ISSUE THREAD

**Issue by arthurdevaux** [WildCodeSchool/feedback#77]
dans la quete " apprendre à apprendre " l'onglet " Sens et stratégie " nous demande de télécharger un lien. Cependant ce lien est payant.

**Comment by Em-AK** [comment]
Hello @arthurdevaux, tu peux me donner le lien exact ?

**Comment by Cookiie** [comment]
hello @arthurdevaux 
peux-tu répondre au commentaire précédent stp ? Ou as-tu trouvé une alternative ?

**Comment by Cookiie** [comment]
ticket resté sans réponse, je ferme
