### ISSUE TITLE
Problème d'affichage des participants d'une quêtes

### ISSUE THREAD

**Issue by jbehuet** [WildCodeSchool/feedback#78]
![capture d ecran 2016-09-05 a 14 26 48](https://cloud.githubusercontent.com/assets/4539599/18247848/41245fc4-7375-11e6-8f8a-85230dc4e697.png)

**Comment by julienr114** [comment]
Oui, c'est noté on est dessus pour un fixe rapide.

**Comment by julienr114** [comment]
![capture d ecran 2016-09-06 a 09 48 04](https://cloud.githubusercontent.com/assets/10990867/18265647/0a2d1a22-7417-11e6-88c9-39fd7a752596.png)
