### ISSUE TITLE
Quest / HTTP Request (JS)

### ISSUE THREAD

**Issue by Ludo-Boa** [WildCodeSchool/feedback#79]
Salut les amis.

Quête non réalisable.
 OpenWeatherMap ne fonctionne pas (je renseigne une ville [ici](http://openweathermap.org/) et cela ne me retourne rien)

**Comment by julienr114** [comment]
Salut @Ludo-Boa,

Effectivement leur site doit rencontrer des soucis et leur champs de recherche ne fonctionne pas. 

En revanche l'API fonctionne bien et c'est l'essentiel pour la quête. Parcours leur [documentation](http://openweathermap.org/current), Tu peux utiliser [postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) pour tester tes requêtes.
N'oublie pas de te créer un compte gratuit pour obtenir une clée d'API et l'ajouté à tes requêtes comme d'écris [ici](http://openweathermap.org/appid).
