### ISSUE TITLE
https://try.github.io/ est inaccessible

### ISSUE THREAD

**Issue by CilooW** [WildCodeSchool/feedback#83]
Bonjour,

Ce matin, j'ai tenté de réaliser la quête sur ce site (dans le tuto Git), mais l'adresse est introuvable, comme si elle n'existait plus. Pourtant, un des élèves m'a dit l'avoir réalisé sans problèmes hier... 

Bonne journée!

**Comment by Em-AK** [comment]
Merci @CilooW pour ce feedback

J'ai mis à jour le lien pour tout le monde dans la quête.
https://www.codeschool.com/courses/try-git

Tu peux me confirmer que c'est bon pour toi ?

**Comment by CilooW** [comment]
Oui, je te confirme que j'y accède, merci :)
