### ISSUE TITLE
Bug detected /quests/7

### ISSUE THREAD

**Issue by Aplmoicam** [WildCodeSchool/feedback#84]
Bonjour ! :) 

Je ne trouve pas le lien vers le dépot pour le challenge.

merci :D

**Comment by Em-AK** [comment]
Hello !
en effet il manquais le lien vers le repo dans le Challenge de la quête.

C'est corrigé :sheep:

**Comment by Aplmoicam** [comment]
Merci :)

2016-09-08 12:02 GMT+02:00 Emilien notifications@github.com:
