### ISSUE TITLE
Bug quête : Apprendre le Markdown

### ISSUE THREAD

**Issue by sbstnplcn** [WildCodeSchool/feedback#85]
Les exercices sont vide + le challenge ne propose pas réellement un exercice d'écriture en Markdown, mais plus une traduction. C'est intéressant pour le coté "git" mais rien a voir avec le Markdown

**Comment by julienr114** [comment]
Effectivement les étapes ne contiennent pas leurs ressources 
![capture d ecran 2016-09-08 a 09 42 46](https://cloud.githubusercontent.com/assets/10990867/18341115/c506782e-75a8-11e6-841f-092362656730.png)
![capture d ecran 2016-09-08 a 09 42 59](https://cloud.githubusercontent.com/assets/10990867/18341116/c50cbee6-75a8-11e6-8597-0d6bb51abdb6.png)

**Comment by edoume** [comment]
@sbstnplcn Merci du signalement, les ressources sont de retour
