### ISSUE TITLE
Quête comprendre git

### ISSUE THREAD

**Issue by annelf** [WildCodeSchool/feedback#86]
Cela fait 2 jours que je cherche comment on peut "dessiner l'arbre" dans son intégralité depuis le dépôt cloné. Il est immense, j'ai bien essayé de faire une sélection partielle d'imprim écran mais ça n'a pas fonctionné. Du coup à part le dessiner à la main je ne vois pas trop comment on peut faire :/

**Comment by Em-AK** [comment]
Je pense que tu trouvera des réponses dans cet article pour explorer le graph d´un repo git visuellement:
http://odyssey.wildcodeschool.fr/shares/197

Ce matin j'ai mis à jour le challenge de **Comprendre git** avec le bon repo à dessiner.

[Voir le challenge à jour](http://odyssey.wildcodeschool.fr/quests/7#challenge)
