### ISSUE TITLE
Lenteur Odyssey

### ISSUE THREAD

**Issue by MkLHX** [WildCodeSchool/feedback#88]
Je ne sais pas combien d'utilisateurs nous sommes sur Odyssey ce jour mais il devient de plus en plus de naviguer et de corriger les quêtes des camarades...

**Comment by MkLHX** [comment]
Peut-on avoir une plateforme qui tourne? Erreur 504 timaout permanente...

**Comment by Cookiie** [comment]
@MkLHX merci pour ton retour, on s'en occupe :)

**Comment by Cookiie** [comment]
@MkLHX nous avons fait pas mal d'optimisation, est-ce que c'est ok de ton côté ?

**Comment by MkLHX** [comment]
@Cookiie désolé mais pour le moment je n'ai pas pratiqué odyssey depuis 2 ou 3 semaines. Je vous fais un retour vers début novembre car je suis à fond sur notre projet 2. De toute façon j'avais prévu de faire un retour dès que je reprends les quêtes.
