### ISSUE TITLE
La navigation mobile n'est pas très intuitive

### ISSUE THREAD

**Issue by cyril-lemaire** [WildCodeSchool/feedback#89]
Le menu du profil "Demander de l'aide / Mes demandes en cours / Mon profil / Déconnexion" est vide en format web et smartphone (testé avec firefox sous Mac et Ubuntu)

**Comment by julienr114** [comment]
Peux-tu nous envoyer un screen-shot de ton problème ? Car cela fonctionne pour moi.
![image1](https://cloud.githubusercontent.com/assets/10990867/18357660/177337d4-75f2-11e6-80de-25242a05fbdc.png)

**Comment by cyril-lemaire** [comment]
Bien sûr ça m'affiche ça : http://imgur.com/a/Zp6vp (et ça n'est pas une question de chargement, le menu déroulant reste vide) Je précise que c'est sur PC avec une fenêtre de taille tablette ou moins, pas sur mon téléphone (PS : branche le tiens avant qu'il ne se décharge totalement :P)

**Comment by julienr114** [comment]
@RandsTaggle 

Le menu se trouve de l'autre coté (le button burger en haut à gauche), l'autre button affiche un menu vide pour le moment qui affichera par la suite d'autres informations lier à la page sur laquelle te trouve. (Dsl, on est un peu en chantier)

Merci de nous avoir remonté ton souci, ça nous permet de nous rendre compte que l'utilisation n'est pas très intuitive.

**Comment by julienr114** [comment]
fixer dans https://github.com/WildCodeSchool/wildboard/pull/1213/commits/822682cf1cb1d0031255402c457b64197abbdd76
