### ISSUE TITLE
leave a quest

### ISSUE THREAD

**Issue by annelf** [WildCodeSchool/feedback#90]
Peut-on quitter une quête ? J'ai eu la riche idée de commencer la quête LinkedIn et du coup je sais qu'elle ne sera pas validée si je mets le lien de mon profil, car tous les crtières de validation ne sont pas remplis encore.

**Comment by edoume** [comment]
Hello @annelf, non une fois engagé tu dois la terminer.
Je vois que @sblondeau te l'as validé il y a 5min, c'est OK pour toi?
Édouard

**Comment by Cookiie** [comment]
Ticket resté sans réponse, je ferme
