### ISSUE TITLE
Impossible de poster solution

### ISSUE THREAD

**Issue by Jasdero** [WildCodeSchool/feedback#96]
Bonjour,
je ne peux pas poster ma solution pour la quete Gist in the CLI.
Pas de message d'erreur particuliere,

juste "something went wrong"

merci

**Comment by Jasdero** [comment]
c'etait une erreur de ma part désolé

**Comment by edoume** [comment]
Je poste une liste de vérif à faire si qqun passe par là ;)

# GIST FIX
- Vérifiez que vous avez bien renseigné votre pseudo GitHub sur votre profil Odyssey
- Postez le lien du Gist en question (il devrait resembler à ceci https://gist.github.com/edoume/1349b76391f3d75ee8fe)
